apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
- ./namespace.yaml
- ./demo.yaml
- ./flask.yaml
- ./service.yaml
- ./flask-service.yaml
- ./ingress.yaml
- ./new-ingress.yaml
